// Generated by CoffeeScript 1.9.2
var dir, file, files, fs, i, len, path, results;

path = require('path');

fs = require('fs');

dir = path.join(process.cwd(), 'wiki');

files = fs.readdirSync(dir);

results = [];

for (i = 0, len = files.length; i < len; i++) {
  file = files[i];
  if (file.substr(-3) !== '.md') {
    continue;
  }
  if (file[0] === '_') {
    continue;
  }
  results.push(file.slice(0, -3));
}

results.sort();

fs.writeFileSync('catalog.json', JSON.stringify(results, null, 2));
