// Generated by CoffeeScript 1.9.2
var component, dom, exe, hub, marked, odoql, ql, ref, relay, renderrichtext, request, root, router, scene, store, widget;

ref = require('odojs'), component = ref.component, widget = ref.widget, hub = ref.hub, dom = ref.dom;

relay = require('odo-relay');

exe = require('odoql-exe');

odoql = require('odoql/odojs');

component.use(odoql);

store = require('odoql-store');

request = require('superagent');

store = store().use('content', function(params, cb) {
  return request.get('README.md').end(function(err, res) {
    if (err != null) {
      return cb(err);
    }
    if (!res.ok) {
      return cb(new Error(res.text));
    }
    return cb(null, res.text);
  });
});

hub = hub();

exe = exe({
  hub: hub
}).use(store);

ql = require('odoql');

ql = ql.use('store');

marked = require('marked');

renderrichtext = widget({
  render: function(state, params) {
    return dom('div.definition');
  },
  afterMount: function(el, state, params) {
    return el.innerHTML = marked(params);
  },
  onUpdate: function(el, state, params) {
    return el.innerHTML = marked(params);
  }
});

router = component({
  query: function(params) {
    return {
      content: ql.store('content')
    };
  },
  render: function(state, params, hub) {
    return dom('#root.container', [
      dom('h4.pull-right', dom('a', {
        attributes: {
          href: 'https://github.com/odojs/odojs.com'
        }
      }, 'GitHub')), dom('h4', dom('a', {
        attributes: {
          href: './'
        }
      }, 'Odo.js')), dom('.row', [
        dom('.col-xs-3.toc', [
          dom('h6', 'Table of contents'), dom('.list-group', [
            dom('a.list-group-item', {
              attributes: {
                href: '#'
              }
            }, 'Item 1'), dom('a.list-group-item', {
              attributes: {
                href: '#'
              }
            }, 'Item 2')
          ])
        ]), dom('.col-xs-9.content', [
          dom('h6.pull-right', dom('a', {
            attributes: {
              href: 'https://github.com/odojs/odojs.com/edit/gh-pages/README.md'
            }
          }, 'pull requests welcome & encouraged')), dom('h6', 'README.md'), renderrichtext(null, state.content)
        ])
      ])
    ]);
  }
});

root = document.querySelector('#root');

scene = relay(root, router, exe, {
  hub: hub
});

scene.update();
