// Generated by CoffeeScript 1.9.2
var component, dom, exe, hub, odoql, ref, relay, root, router, scene;

ref = require('odojs'), component = ref.component, hub = ref.hub, dom = ref.dom;

exe = require('odoql-exe');

relay = require('odo-relay');

odoql = require('odoql/odojs');

component.use(odoql);

hub = hub();

exe = exe({
  hub: hub
});

router = component({
  render: function(state, params, hub) {
    if (params.autocomplete == null) {
      params.autocomplete = {};
    }
    return dom('#root', [dom('p', 'Some trash here')]);
  }
});

root = document.querySelector('#root');

scene = relay(root, router, exe, {
  hub: hub
});

hub.every('update', function(p, cb) {
  scene.update(p);
  return cb();
});

scene.update({});
