// Generated by CoffeeScript 1.9.2
var whakaruru;

whakaruru = require('whakaruru');

whakaruru(function() {
  var app, express, mutunga, pjson, port, server;
  express = require('express');
  app = express();
  require('./server/static')(app);
  require('./server/root')(app);
  mutunga = require('http-mutunga');
  pjson = require('./package.json');
  port = 8080;
  return server = mutunga(app).listen(port, function() {
    var boundport, host, shutdown;
    host = server.address().address;
    boundport = server.address().port;
    shutdown = function() {
      console.log(pjson.name + "@" + pjson.version + " ōhākī waiting for requests to finish");
      return server.close(function() {
        console.log(pjson.name + "@" + pjson.version + " e noho rā!");
        return process.exit(0);
      });
    };
    console.log(pjson.name + "@" + pjson.version + " has started listening on " + host + ":" + boundport);
    process.on('SIGTERM', shutdown);
    return process.on('SIGINT', shutdown);
  });
});
