// Generated by CoffeeScript 1.9.2
var path;

path = require('path');

module.exports = function(app) {
  return app.get('/*', function(req, res, next) {
    return res.sendFile(path.resolve(__dirname, '../index.html'));
  });
};
