// Generated by CoffeeScript 1.9.2
module.exports = function(app) {
  var cors, express, oneDay, path;
  path = require('path');
  cors = require('cors');
  express = require('express');
  oneDay = 1000 * 60 * 60 * 24;
  return app.use('/dist', [
    cors(), express["static"](path.join(__dirname, '../', 'dist'), {
      maxAge: oneDay
    })
  ]);
};
